Filter containers by label

diff --git a/docker-label-sighup b/docker-label-sighup
--- a/docker-label-sighup
+++ b/docker-label-sighup
@@ -1,25 +1,32 @@
 #!/bin/bash
 
 function docker_api {
-    local scheme
-    local curl_opts=(-s)
+    local host
+    local path=${1:-/}
     local method=${2:-GET}
-    # data to POST
-    if [[ -n "${3:-}" ]]; then
-        curl_opts+=(-d "$3")
+    local data=${3:-}
+    local curl_opts=(-s)
+
+    if [ "$method" = 'POST' ]; then
+        curl_opts+=(-d "$data")
+        if [ -n "$data" ]; then
+            curl_opts+=(-H 'Content-Type: application/json')
+        fi
+    elif [ -n "$data" ]; then
+        curl_opts+=(--get)
+        curl_opts+=(--data-urlencode "$data")
     fi
-    if [[ -z "$DOCKER_HOST" ]];then
+    if [ -z "$DOCKER_HOST" ];then
         echo "Error DOCKER_HOST variable not set" >&2
         return 1
     fi
-    if [[ $DOCKER_HOST == unix://* ]]; then
+    if [ -n "${DOCKER_HOST#unix://}" ]; then
         curl_opts+=(--unix-socket ${DOCKER_HOST#unix://})
-        scheme='http://localhost'
+        host='http://localhost'
     else
-        scheme="http://${DOCKER_HOST#*://}"
+        host="http://${DOCKER_HOST#*://}"
     fi
-    [[ $method = "POST" ]] && curl_opts+=(-H 'Content-Type: application/json')
-    curl "${curl_opts[@]}" -X${method} ${scheme}$1
+    curl "${curl_opts[@]}" ${host}$path
 }
 
 function docker_kill {
@@ -28,10 +35,13 @@ function docker_kill {
     docker_api "/containers/$id/kill?signal=$signal" "POST"
 }
 
-labeled_cid=$(docker_api "/containers/json" | jq -r '.[] | select(.Labels["'$1'"])|.Id')
-if [[ -z "${labeled_cid:-}" ]]; then
-    echo "Error: can't get container id for label '$1'" >&2
+containers=$(docker_api "/containers/json" "GET" 'filters={"label": ["'$1'"]}' | jq -r '[.[] | .Id] | join(" ")')
+if [ -z "${containers:-}" ]; then
+    echo "Error: can't get containers for label '$1'" >&2
     exit 1
 fi
 
-docker_kill "$labeled_cid" SIGHUP
+for cid in ${containers}; do
+    echo "Sending SIGHUP to $cid..."
+    docker_kill "$cid" SIGHUP
+done
